name: Coleta diária PNCP

on:
  schedule:
    - cron: '0 6 * * 1-5'
  workflow_dispatch:

jobs:
  coleta-pncp:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: npm install

      - name: Instalar navegador do Puppeteer
        run: npx puppeteer install

      - name: Executar todos os scripts de coleta
        run: npm run coletar

      - name: Commit e push de novos dados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add dados/
          if git diff --cached --quiet; then
            echo "Nenhuma alteração detectada."
          else
            git commit -m "Atualização diária automática"
            git push
          fi
